package com.cursor_springa_ai.playground.model;

import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MapsId;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * End-of-day portfolio snapshot for a single holding.
 *
 * <p>Written once per (user, instrument, date) — duplicate writes for the same date are silently
 * skipped. The composite primary key enforces this uniqueness at the database level.
 *
 * <p>The {@code id} column is a BIGSERIAL / IDENTITY column managed by the database; it is
 * included for convenient external referencing but is not the JPA identifier.
 */
@Entity
@Table(name = "holding_snapshots")
public class HoldingSnapshot {

    /**
     * Auto-incremented surrogate column generated by the database.
     * Not the JPA identifier — use {@link #pk} for entity identity.
     */
    @Column(name = "id", nullable = false, insertable = false, updatable = false,
            columnDefinition = "BIGINT GENERATED BY DEFAULT AS IDENTITY")
    private Long id;

    /** Composite primary key: (user_id, instrument_token, snapshot_date). */
    @EmbeddedId
    private HoldingSnapshotId pk;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @MapsId("userId")
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @MapsId("instrumentToken")
    @JoinColumn(name = "instrument_token", nullable = false)
    private Instrument instrument;

    @Column(nullable = false)
    private Integer quantity;

    @Column(name = "avg_price", nullable = false, precision = 18, scale = 4)
    private BigDecimal avgPrice;

    @Column(name = "close_price", nullable = false, precision = 18, scale = 4)
    private BigDecimal closePrice;

    @Column(name = "invested_value", nullable = false, precision = 18, scale = 4)
    private BigDecimal investedValue;

    @Column(name = "market_value", nullable = false, precision = 18, scale = 4)
    private BigDecimal marketValue;

    @Column(nullable = false, precision = 18, scale = 4)
    private BigDecimal pnl;

    @Column(name = "weight_percent", precision = 10, scale = 4)
    private BigDecimal weightPercent;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    protected HoldingSnapshot() {
    }

    public HoldingSnapshot(User user, Instrument instrument, LocalDate snapshotDate,
                           Integer quantity, BigDecimal avgPrice, BigDecimal closePrice,
                           BigDecimal investedValue, BigDecimal marketValue,
                           BigDecimal pnl, BigDecimal weightPercent) {
        this.pk = new HoldingSnapshotId(user.getId(), instrument.getInstrumentToken(), snapshotDate);
        this.user = user;
        this.instrument = instrument;
        this.quantity = quantity;
        this.avgPrice = avgPrice;
        this.closePrice = closePrice;
        this.investedValue = investedValue;
        this.marketValue = marketValue;
        this.pnl = pnl;
        this.weightPercent = weightPercent;
    }

    public Long getId() {
        return id;
    }

    public HoldingSnapshotId getPk() {
        return pk;
    }

    public User getUser() {
        return user;
    }

    public Instrument getInstrument() {
        return instrument;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public BigDecimal getAvgPrice() {
        return avgPrice;
    }

    public BigDecimal getClosePrice() {
        return closePrice;
    }

    public BigDecimal getInvestedValue() {
        return investedValue;
    }

    public BigDecimal getMarketValue() {
        return marketValue;
    }

    public BigDecimal getPnl() {
        return pnl;
    }

    public BigDecimal getWeightPercent() {
        return weightPercent;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
